# Generated by Django 2.1.3 on 2018-11-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_ma', models.CharField(max_length=100, verbose_name='A_Field')),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_mb', models.CharField(max_length=100, verbose_name='B_Field')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_01.A')),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_mc', models.CharField(max_length=100, verbose_name='C_Field')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_01.A')),
            ],
        ),
    ]
